//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspberryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Friday = new HashSet<Friday>();
            this.Monday = new HashSet<Monday>();
            this.Saturday = new HashSet<Saturday>();
            this.Sunday = new HashSet<Sunday>();
            this.TasksFolder1 = new HashSet<TasksFolder1>();
            this.TasksFolder2 = new HashSet<TasksFolder2>();
            this.TasksFolder3 = new HashSet<TasksFolder3>();
            this.Thursday = new HashSet<Thursday>();
            this.Tuesday = new HashSet<Tuesday>();
            this.Wednesday = new HashSet<Wednesday>();
        }
    
        public string CategoryId { get; set; }
    
        public virtual ICollection<Friday> Friday { get; set; }
        public virtual ICollection<Monday> Monday { get; set; }
        public virtual ICollection<Saturday> Saturday { get; set; }
        public virtual ICollection<Sunday> Sunday { get; set; }
        public virtual ICollection<TasksFolder1> TasksFolder1 { get; set; }
        public virtual ICollection<TasksFolder2> TasksFolder2 { get; set; }
        public virtual ICollection<TasksFolder3> TasksFolder3 { get; set; }
        public virtual ICollection<Thursday> Thursday { get; set; }
        public virtual ICollection<Tuesday> Tuesday { get; set; }
        public virtual ICollection<Wednesday> Wednesday { get; set; }
    }
}
