//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspberryNote
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaspberryNoteEntities : DbContext
    {
        public RaspberryNoteEntities()
            : base("name=RaspberryNoteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Friday> Friday { get; set; }
        public DbSet<Monday> Monday { get; set; }
        public DbSet<Saturday> Saturday { get; set; }
        public DbSet<Sunday> Sunday { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TasksFolder1> TasksFolder1 { get; set; }
        public DbSet<TasksFolder2> TasksFolder2 { get; set; }
        public DbSet<TasksFolder3> TasksFolder3 { get; set; }
        public DbSet<Thursday> Thursday { get; set; }
        public DbSet<Tuesday> Tuesday { get; set; }
        public DbSet<Wednesday> Wednesday { get; set; }
    }
}
