//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspberryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksFolder3
    {
        public int NoteId { get; set; }
        public Nullable<System.DateTime> NoteDateCreated { get; set; }
        public string NoteDescription { get; set; }
        public string NoteState { get; set; }
        public Nullable<System.DateTime> NoteFinishDate { get; set; }
        public string NoteCategory { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
