//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspberryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuesday
    {
        public int DNoteId { get; set; }
        public string DNoteDescription { get; set; }
        public string DNoteCategory { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
